### ISSUE TITLE
idea: google cast btn in player

### ISSUE THREAD

**Issue by qveezzx** [Unofficial-Filman-Client/unofficial-filman-client#16]
You could implement something like cast to tv button in player yk.

**Comment by majusss** [comment]
good idea, now I only support hosting with direct access to the video file so this can be done by [flutter_cast_video package](https://pub.dev/packages/flutter_cast_video)

**Comment by qveezzx** [comment]
edit:
tried doing it myself but theres tooooo much of work to make it work, still would need to make it cast only phone screen which is option in most androids.

**Comment by majusss** [comment]
> edit:
> tried doing it myself but theres tooooo much of work to make it work, still would need to make it cast only phone screen which is option in most androids.

i checked the package i mentioned earlier and the app crashes on launch

**Comment by qveezzx** [comment]
> > edit:
> > tried doing it myself but theres tooooo much of work to make it work, still would need to make it cast only phone screen which is option in most androids.
> 
> I checked the package I mentioned earlier and the app crashes on launch

so i need to make code for this button myself, right?

**Comment by majusss** [comment]
> > > edit:
> > > tried doing it myself but theres tooooo much of work to make it work, still would need to make it cast only phone screen which is option in most androids.
> > 
> > I checked the package I mentioned earlier and the app crashes on launch
> 
> so i need to make code for this button myself, right?

I've seen a lot of packages that allow Google Cast, something I've tried to use is https://pub.dev/packages/flutter_chrome_cast but I got an error when trying to search for devices

**Comment by qveezzx** [comment]
> > > > edit:
> > > > tried doing it myself but theres tooooo much of work to make it work, still would need to make it cast only phone screen which is option in most androids.
> > > 
> > > 
> > > I checked the package I mentioned earlier and the app crashes on launch
> > 
> > 
> > so i need to make code for this button myself, right?
> 
> I've seen a lot of packags that allow Google Cast try https://pub.dev/packages/flutter_chrome_cast I got an error when searching for devices

could you post edited files code in here? i never tried adding things like video casting etc. to my android projects, just wanted to see how is it done to recreate it myself, if i would release it, ill make sure to credit you and this repo, just using it as a base.

**Comment by majusss** [comment]
> > > > > edit:
> > > > > tried doing it myself but theres tooooo much of work to make it work, still would need to make it cast only phone screen which is option in most androids.
> > > > 
> > > > 
> > > > I checked the package I mentioned earlier and the app crashes on launch
> > > 
> > > 
> > > so i need to make code for this button myself, right?
> > 
> > I've seen a lot of packags that allow Google Cast try https://pub.dev/packages/flutter_chrome_cast I got an error when searching for devices
> 
> could you post edited files code in here? i never tried adding things like video casting etc. to my android projects, just wanted to see how is it done to recreate it myself, if i would release it, ill make sure to credit you and this repo, just using it as a base. btw, polak czy nie?

polak xd

**Comment by qveezzx** [comment]
> > > > > > edit:
> > > > > > tried doing it myself but theres tooooo much of work to make it work, still would need to make it cast only phone screen which is option in most androids.
> > > > > 
> > > > > 
> > > > > I checked the package I mentioned earlier and the app crashes on launch
> > > > 
> > > > 
> > > > so i need to make code for this button myself, right?
> > > 
> > > 
> > > I've seen a lot of packags that allow Google Cast try https://pub.dev/packages/flutter_chrome_cast I got an error when searching for devices
> > 
> > 
> > could you post edited files code in here? i never tried adding things like video casting etc. to my android projects, just wanted to see how is it done to recreate it myself, if i would release it, ill make sure to credit you and this repo, just using it as a base. btw, polak czy nie?
> 
> polak xd

o no to super, masz cos z kodu jeszcze zebym mogl obczaic co i jak? bo w tych castach i tego typu rzeczach to akurat jeszcze nie ogarniam

**Comment by majusss** [comment]
> > > > > > > edit:
> > > > > > > tried doing it myself but theres tooooo much of work to make it work, still would need to make it cast only phone screen which is option in most androids.
> > > > > > 
> > > > > > 
> > > > > > I checked the package I mentioned earlier and the app crashes on launch
> > > > > 
> > > > > 
> > > > > so i need to make code for this button myself, right?
> > > > 
> > > > 
> > > > I've seen a lot of packags that allow Google Cast try https://pub.dev/packages/flutter_chrome_cast I got an error when searching for devices
> > > 
> > > 
> > > could you post edited files code in here? i never tried adding things like video casting etc. to my android projects, just wanted to see how is it done to recreate it myself, if i would release it, ill make sure to credit you and this repo, just using it as a base. btw, polak czy nie?
> > 
> > polak xd
> 
> o no to super, masz cos z kodu jeszcze zebym mogl obczaic co i jak? bo w tych castach i tego typu rzeczach to akurat jeszcze nie ogarniam

nie mam na razie czasu siedzieć przy tym

**Comment by qveezzx** [comment]
> > > > > > > > edit:
> > > > > > > > tried doing it myself but theres tooooo much of work to make it work, still would need to make it cast only phone screen which is option in most androids.
> > > > > > > 
> > > > > > > 
> > > > > > > I checked the package I mentioned earlier and the app crashes on launch
> > > > > > 
> > > > > > 
> > > > > > so i need to make code for this button myself, right?
> > > > > 
> > > > > 
> > > > > I've seen a lot of packags that allow Google Cast try https://pub.dev/packages/flutter_chrome_cast I got an error when searching for devices
> > > > 
> > > > 
> > > > could you post edited files code in here? i never tried adding things like video casting etc. to my android projects, just wanted to see how is it done to recreate it myself, if i would release it, ill make sure to credit you and this repo, just using it as a base. btw, polak czy nie?
> > > 
> > > 
> > > polak xd
> > 
> > 
> > o no to super, masz cos z kodu jeszcze zebym mogl obczaic co i jak? bo w tych castach i tego typu rzeczach to akurat jeszcze nie ogarniam
> 
> nie mam na razie czasu siedzieć przy tym

rozumiem, dzieki za odpowiedz, milego dnia.

**Comment by majusss** [comment]
nawet example z tej libki nie dziala XD
https://github.com/felnanuke2/flutter_google_cast/issues/3#issuecomment-2211847792

**Comment by qveezzx** [comment]
> nawet example z tej libki nie dziala XD [felnanuke2/flutter_google_cast#3 (comment)](https://github.com/felnanuke2/flutter_google_cast/issues/3#issuecomment-2211847792)

czyli niepotrzebnie sie niedawno bawilem XD, doslownie jak ty odpisales to skompilowalem i sie okazalo ze cos z*ebane

**Comment by majusss** [comment]
> > nawet example z tej libki nie dziala XD [felnanuke2/flutter_google_cast#3 (comment)](https://github.com/felnanuke2/flutter_google_cast/issues/3#issuecomment-2211847792)
> 
> czyli niepotrzebnie sie niedawno bawilem XD, doslownie jak ty odpisales to skompilowalem i sie okazalo ze cos z*ebane

ta, też próbowałem tego użyć w apce, też nie działa

**Comment by qveezzx** [comment]
najszybszym sposobem bylo po prostu zrobienie przycisku z ikona cast, uzycie plugina android_intent_plus i ogarniecie skryptu tak zeby pokazywal opcje udostepniania ekranu ta defaultowa z systemu, moze nie najlepsze rozwiazanie ale szybkie i skuteczne

**Comment by majusss** [comment]
> najszybszym sposobem bylo po prostu zrobienie przycisku z ikona cast, uzycie plugina android_intent_plus i ogarniecie skryptu tak zeby pokazywal opcje udostepniania ekranu ta defaultowa z systemu, moze nie najlepsze rozwiazanie ale szybkie i skuteczne

kilka problemów:
1. ekran hosta musi być włączony
2. kompresja i straty jakości
3. skoro mamy direct do video to słabo to zmarnować

**Comment by qveezzx** [comment]
> > najszybszym sposobem bylo po prostu zrobienie przycisku z ikona cast, uzycie plugina android_intent_plus i ogarniecie skryptu tak zeby pokazywal opcje udostepniania ekranu ta defaultowa z systemu, moze nie najlepsze rozwiazanie ale szybkie i skuteczne
> 
> kilka problemów:
> 1. ekran hosta musi być włączony
> 2. kompresja i straty jakości
> 3. skoro mamy direct do video to słabo to zmarnować
> 


1. zależy od systemu
2. zależy od prędkości internetu
3. coś się uda zdziałać

**Comment by qveezzx** [comment]
jeszcze dwie rzeczy, jaki jest format plików wideo i jak wybiera hosty? tzn. jest lista hostów, podłóg czego wybiera aplikacja?

**Comment by majusss** [comment]
> jeszcze dwie rzeczy, jaki jest format plików wideo i jak wybiera hosty? tzn. jest lista hostów, podłóg czego wybiera aplikacja?

aktualnie scrapuje tylko videoze bo ma chyba mp4 player zwykły w kodzie strony, można zobaczyć

**Comment by qveezzx** [comment]
> > jeszcze dwie rzeczy, jaki jest format plików wideo i jak wybiera hosty? tzn. jest lista hostów, podłóg czego wybiera aplikacja?
> 
> aktualnie scrapuje tylko videoze bo ma chyba mp4 player zwykły w kodzie strony, można zobaczyć 

to jak teraz myślałem można zrobić tak aby używało innego hosta jeśli np na danym hoście nie ma jakiegoś filmu, chyba dałoby się coś takiego zrobić, prawda? 

edit: masz discord? zeby się jakoś kontaktować bo ten projekt mnie strasznie zaciekawił a tu na githubie tak nie wypada zapychać issues

**Comment by majusss** [comment]
> > > jeszcze dwie rzeczy, jaki jest format plików wideo i jak wybiera hosty? tzn. jest lista hostów, podłóg czego wybiera aplikacja?
> > 
> > aktualnie scrapuje tylko videoze bo ma chyba mp4 player zwykły w kodzie strony, można zobaczyć 
> 
> to jak teraz myślałem można zrobić tak aby używało innego hosta jeśli np na danym hoście nie ma jakiegoś filmu, chyba dałoby się coś takiego zrobić, prawda? 
> 
> edit: masz discord? zeby się jakoś kontaktować bo ten projekt mnie strasznie zaciekawił a tu na githubie tak nie wypada zapychać issues

większość hostów aktualnie działa na streamy albo na segmentach ciężko to scrapowac ale pewnie wszystko się da

dc: .majus.

**Comment by qveezzx** [comment]
> > > > jeszcze dwie rzeczy, jaki jest format plików wideo i jak wybiera hosty? tzn. jest lista hostów, podłóg czego wybiera aplikacja?
> > > 
> > > 
> > > aktualnie scrapuje tylko videoze bo ma chyba mp4 player zwykły w kodzie strony, można zobaczyć
> > 
> > 
> > to jak teraz myślałem można zrobić tak aby używało innego hosta jeśli np na danym hoście nie ma jakiegoś filmu, chyba dałoby się coś takiego zrobić, prawda?
> > edit: masz discord? zeby się jakoś kontaktować bo ten projekt mnie strasznie zaciekawił a tu na githubie tak nie wypada zapychać issues
> 
> większość hostów aktualnie działa na streamy albo na segmentach ciężko to scrapowac ale pewnie wszystko się da
> 
> dc: .majus.

dodalem
