### ISSUE TITLE
Add support for more sites

### ISSUE THREAD

**Issue by GrafKiedyOdcinek** [Unofficial-Filman-Client/unofficial-filman-client#24]
I really like this app, but the fact that it only supports vidoza currently limits the amount of movies and shows a lot, making the app almost useless.
Below are my suggestions, starting from my favourite sites.
~~1.vtube.network~~
2.voe.sx
3.doodstream.com
~~4.streamtape.com~~
5.vid-guard.com

**Comment by majusss** [comment]
It's my long-term goal, but I don't have an idea of how to implement these sites because I use a multi-platform video player called (MediaKit)[https://pub.dev/packages/media_kit] that doesn't support video streams—it only works with direct video links.

**Comment by GrafKiedyOdcinek** [comment]
Maybe you should switch to something that supports the m3u8 format.

**Comment by majusss** [comment]
MediaKit support streams, I tested it now.

**Comment by majusss** [comment]
> I really like this app, but the fact that it only supports vidoza currently limits the amount of movies and shows a lot, making the app almost useless. Below are my suggestions, starting from my favourite sites. 1.vtube.network 2.voe.sx 3.doodstream.com 4.streamtape.com 5.vid-guard.com

after [long battle](https://github.com/Unofficial-Filman-Client/unofficial-filman-client/blob/f284ebc3a68e83ba695c9d4775afc0dd26db40f7/lib/utils/hosts.dart#L128) with encryptio, vtube will be supporten in 1.3.0.

**Comment by majusss** [comment]
Streamtape is [supported ](https://github.com/Unofficial-Filman-Client/unofficial-filman-client/commit/94206b44551d8150f16adf2c5c895388bd235350) since 1.0.1.

**Comment by majusss** [comment]
I should create a list of issues with all existing video providers on Filman and specify which hosts are supported, which are not, and which ones I am working on.
