### ISSUE TITLE
video size

### ISSUE THREAD

**Issue by arczi033** [Unofficial-Filman-Client/unofficial-filman-client#33]
please add option - video resize - fit to screen

**Comment by majusss** [comment]
Yes, it's a todo. sorry for the late reply

**Comment by arczi033** [comment]
if the series has a lot of episodes they take a long time to load, they are sorted incorrectly, episode no. 100 is before 11

**Comment by majusss** [comment]
> if the series has a lot of episodes they take a long time to load, they are sorted incorrectly, episode no. 100 is before 11

You should make separated issues for this. (wich series has 100 episoed?)

**Comment by arczi033** [comment]
for example look at the dragon ball z series, the episodes are sorted in the following way: first the hundreds digit, then the tens digit and finally the ones digit (this is how it is displayed for me), the episodes load slowly, you have to wait a long time to open the episode e.g. number 100

**Comment by majusss** [comment]
> for example look at the dragon ball z series, the episodes are sorted in the following way: first the hundreds digit, then the tens digit and finally the ones digit (this is how it is displayed for me), the episodes load slowly, you have to wait a long time to open the episode e.g. number 100 

You don't have to wait for the episode to load. It only loads the description, and you can play any episode without waiting just by clicking on it.
I will fix issue with sorting in 1.3.3

**Comment by arczi033** [comment]
the problem is that the episodes cannot be played

**Comment by arczi033** [comment]
I updated the app, sorting works, descriptions still take a long time to load, I can't play the episode whose description is loading (message: no links), the video starts only when the description is loaded, as I said, I have to wait a long time to start e.g. episode number 100, I tested on Samsung and Xiaomi devices with Android 12

**Comment by majusss** [comment]
So when episode is loading the player displays no links message but when it loads the same episode works?

**Comment by arczi033** [comment]
video
https://drive.google.com/file/d/1iJ5aeZEkzYVJk9YIh8kACXgWJRVGPG-q/view?usp=sharing

**Comment by majusss** [comment]
I think its work but there are no supported hosts for episode 100. I have better question, why player not rotating screen to landscape xd?

**Comment by arczi033** [comment]
I just have forced full rotation on my phone., video in landscape orientation works fine, I don't know what "no supported hosts" means but video on the filman site works all episodes I've checked

**Comment by majusss** [comment]
This app currently support only 3 hosting websites that filman use #32

**Comment by arczi033** [comment]
ok I understand now, I use the premium player on the filman website but this application only supports 3 free hostings where the video is not available, everything is clear

**Comment by majusss** [comment]
I dont have access to premium account so i cant implement that player for now

**Comment by arczi033** [comment]
thanks for your help, the issue can be closed
