### ISSUE TITLE
Capatcha Filman

### ISSUE THREAD

**Issue by flixcard** [Unofficial-Filman-Client/unofficial-filman-client#36]
Poprawisz capatche w aplikacji ? Bo nie można się zalogować.
Będzie ta aplikacja dziłać na smart tv? (chodzi mi o poruszanie się po menu?)

**Comment by majusss** [comment]
Biorę się za captche, odnośnie android tv flutter chyba oficjalnie nie daje żadnej metody budowania komponentów żeby działały z pilotem.

**Comment by flixcard** [comment]
Dzięki teraz śmiga :) Muszę protestować czy jakoś z android tv by zadziałało. Ew. to przesyłanie obrazu ale nie wiem czy działa.

**Comment by majusss** [comment]
Działa raczej znośnie
