### ISSUE TITLE
nieoficjalny klient-filman

### ISSUE THREAD

**Issue by RagnarLodbrok1981** [Unofficial-Filman-Client/unofficial-filman-client#40]
Good morning, a very nice add-on, unfortunately on Android TV it doesn't work after logging in to premium, then a message pops up saying that I filled in the "captcha" incorrectly - is there any way to fix it? Regards

**Comment by rafalmar1981** [comment]
@majusss 
Thank you very much, good luck and best regards

**Comment by majusss** [comment]
Check [1.3.5](https://github.com/Unofficial-Filman-Client/unofficial-filman-client/releases/tag/1.3.5) and give me feedback.

**Comment by rafalmar1981** [comment]
Hello, so I installed this new version, logging in with nickname and password, no captcha error appears when logging in. It spins around for five minutes and nothing happens, the same when logging in via e-mail :( it's a pity. Regards

**Comment by majusss** [comment]
A record screen of this issue will be helpfull. How it should look like:
https://github.com/user-attachments/assets/bbff8a84-8db3-4799-9ffd-49ab0f5fae74

**Comment by rafalmar1981** [comment]
everything looks the same as for you, I enter the logo, password and click log in - only for me the captcha does not pop up and the login wheel keeps spinning and nothing happens, this is what it looks like on my TV Manta - Android 7. I checked it now on a Huawei smartphone mate 20 lite android 8, just out of curiosity and it works on my phone, my Manta TV has android 7 maybe that's why.  Well, you can't have everything. Regards

**Comment by toso-7** [comment]
> Good morning, a very nice add-on, unfortunately on Android TV it doesn't work after logging in to premium, then a message pops up saying that I filled in the "captcha" incorrectly - is there any way to fix it? Regards

https://filman.cc/public/FilmanTV.apk

**Comment by rafalmar1981** [comment]
@toso-7 to lipa straszna logowanie Oki przegląd Oki nic nie da się odtworzyć żadnego źródła czy m3u8 czy mp4

**Comment by majusss** [comment]
> @toso-7 to lipa straszna logowanie Oki przegląd Oki nic nie da się odtworzyć żadnego źródła czy m3u8 czy mp4

Nie rozumiem o co chodzi

**Comment by majusss** [comment]
> > Good morning, a very nice add-on, unfortunately on Android TV it doesn't work after logging in to premium, then a message pops up saying that I filled in the "captcha" incorrectly - is there any way to fix it? Regards
> 
> https://filman.cc/public/FilmanTV.apk

Idk how filman's premium account works, i don't have access to any so i can't make support for it.

**Comment by rafalmar1981** [comment]
this app does not work properly on my Manta TV with Android 7, to log in to it you need to have a premium account and log in using the email you provided when registering the account. So once I log in, I can choose between m3u8 and mp4 playback options in a movie and neither of them works, and I checked it on several dozen movies. So for me this is terrible. Maybe Android is too weak because I have 7 on Manta TV, [unofficial-filmman-client] doesn't even log in on TV, but Android 8 works fine on Huawei 20 Lite Mate

**Comment by toso-7** [comment]
> @toso-7 to lipa straszna logowanie Oki przegląd Oki nic nie da się odtworzyć żadnego źródła czy m3u8 czy mp4

U mnie na Nvidia SHIELD TV Android TV 11 po zalogowaniu na konto premium wszystko odtwarza się bez problemu czy to mp4 czy m3u.

**Comment by majusss** [comment]
> > @toso-7 to lipa straszna logowanie Oki przegląd Oki nic nie da się odtworzyć żadnego źródła czy m3u8 czy mp4
> 
> U mnie na Nvidia SHIELD TV Android TV 11 po zalogowaniu na konto premium wszystko odtwarza się bez problemu czy to mp4 czy m3u. 

Super, coś jeszcze czy mogę zamykać issuesa

**Comment by majusss** [comment]
Ewentualnie mógłbym pewnie zrobić jakiś support dla kont premium jakbym miał takowe konto

**Comment by rafalmar1981** [comment]
podaj meila

**Comment by majusss** [comment]
> podaj meila

majchermajus@proton.me

**Comment by rafalmar1981** [comment]
@majusss spoczko poszło :)

**Comment by rafalmar1981** [comment]
@toso-7 no to widzisz na tv Manta z androidem już nie idzie

**Comment by toso-7** [comment]
Liczmy, że w niedalekiej przyszłości FilmanCC Flutter zacznie działać też na Android TV bo ta apka co podałem wcześniej pokazuje tylko materiały premium, a nie podane przez innych użytkowników 😕

**Comment by majusss** [comment]
> Liczmy, że w niedalekiej przyszłości FilmanCC Flutter zacznie działać też na Android TV bo ta apka co podałem wcześniej pokazuje tylko materiały premium, a nie podane przez innych użytkowników 😕

#42

**Comment by rafalmar1981** [comment]
Dajcie chłopakowi odpocząć, może coś wymyśli, a może nie - stara się i kombinuje...czas na odpoczynek też jest potrzebny by ze świeżą głową podejść ale i nie koniecznie pozdrawiam.

**Comment by 777martin777** [comment]
Świetna aplikacja Przydałyby się takie na zaluknij.cc i e-kino. XD

**Comment by majusss** [comment]
Zapraszam do kontrybucji
