### ISSUE TITLE
FireTV

### ISSUE THREAD

**Issue by keczup21** [Unofficial-Filman-Client/unofficial-filman-client#47]
Cześć,
Jest możliwość użycia tej aplikacji na FireTV 4k 2023? Niestety brak androida i iOS z jailbreakiem :/. Możliwe jest użycie jakiegoś emulatora androida na komputerze do zalogowania się na Firesticku?

**Comment by majusss** [comment]
Jak bardzo chcesz kombinować to możesz wysłać na serwer websocket(na ip firetv, port 3031) wiadomość "LOGIN:$login|$cookies" gdzie login to nazwa użytkownika a cookies to lista ciastek z przeglądarki oddzielnych przecinkiem
przykład: "LOGIN:majusss|PHPSESSID=abc,CIACHO=bcd"
