### ISSUE TITLE
Przeglądanie kategorii

### ISSUE THREAD

**Issue by NeGroRA** [Unofficial-Filman-Client/unofficial-filman-client#49]
Witam będzie kiedyś możliwość wybierania kategorii,
W aplikacji

**Comment by majusss** [comment]
jakiej kategorii?

**Comment by NeGroRA** [comment]
Tak jak jest na stronie internetowej

**Comment by majusss** [comment]
jak mi za to zaczną płacić. Pozdrawiam

**Comment by majusss** [comment]
in progress

![Screenshot_20241112-232253_Unofficial Filman Client.png](https://github.com/user-attachments/assets/a8114f9a-a623-4476-853e-f9868ddb6f1a)

**Comment by majusss** [comment]
Dostępne w [1.4.3](https://github.com/Unofficial-Filman-Client/unofficial-filman-client/releases/tag/1.4.3)

**Comment by NeGroRA** [comment]
@majusss a jest możliwość dodania do aplikacji na tv tych kategorii

**Comment by majusss** [comment]
mało czasu narazie mam a muszę całkiem przerobić to ui na tv
